name: diary
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: 
  cupertino_icons: ^1.0.8
  lottie: ^3.1.0
  table_calendar: ^3.0.9
  fl_chart: ^0.66.2
  uuid: ^4.3.3
  sqflite: ^2.3.2
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/bg_light.jpg
    - assets/bg_dark.jpg
    - assets/icon.png
    - assets/splash.gif

    # Emotion GIFs
    - assets/emotions/happy_emoji.gif
    - assets/emotions/sad_emoji.gif
    - assets/emotions/angry_emoji.gif
    - assets/emotions/excited_emoji.gif
    - assets/emotions/calm_emoji.gif
    - assets/emotions/neutral_emoji.gif

    # Animated feedbacks
    - assets/animations/saving.gif
    - assets/animations/favorite.gif

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
